global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "forecast"
    static_configs:
      - targets: ["forecast:8001"]
  - job_name: "decision"
    static_configs:
      - targets: ["decision:8002"]
